// apps/client/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <div class="min-h-screen flex flex-col bg-gradient-to-b from-blue-50 to-white">
      <!-- Header -->
      <header class="bg-white shadow flex items-center h-16 px-8">
        <span class="font-bold text-2xl text-blue-700 tracking-tight">
          AI Invest Assistant
        </span>
        <!-- (Optional) Add navigation here in the future -->
      </header>

      <!-- Main content -->
      <main class="flex-1 flex flex-col items-center justify-center px-4 py-8">
        <router-outlet></router-outlet>
      </main>

      <!-- (Optional) Footer -->
      <!--
      <footer class="bg-white border-t py-2 text-sm text-gray-400 text-center">
        &copy; {{ year }} AI Invest Assistant
      </footer>
      -->
    </div>
  `,
  styles: [``],
})
export class AppComponent {
  year = new Date().getFullYear();
}

// apps/host/src/app/app.tsx
import  { Suspense, lazy } from 'react';
import { Routes, Route } from 'react-router-dom';
import NavBar from './components/NavBar';
import { HostWelcome } from './components/HostWelcome';
import { ErrorBoundary } from './components/ErrorBoundary';

const DashboardPage = lazy(() => import('dashboard/DashboardPage'));
const UploadPage = lazy(() => import('upload/UploadPage'));



export default function App() {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-blue-50 to-slate-100">
      <NavBar />
      <main className="flex-1 flex flex-col items-center py-8 px-4">
        <div className="w-full max-w-3xl">
          <Routes>
            <Route
              path="/"
              element={
                <div className="bg-white rounded-2xl shadow-xl p-10 mt-8 flex flex-col items-center">
                  <HostWelcome />
                  <div className="mt-6 text-center">
                    <h2 className="text-xl font-bold text-blue-600 mb-2">
                      👋 Welcome to the AI Invest Assistant Host App
                    </h2>
                    <p className="text-gray-700">
                      Use the navigation bar to access Dashboard or Upload.
                    </p>
                  </div>
                </div>
              }
            />
            <Route
              path="dashboard/*"
              element={
                <ErrorBoundary>
                  <Suspense
                    fallback={
                      <div className="text-blue-700 text-lg mt-20 text-center">
                        Loading dashboard…
                      </div>
                    }
                  >
                    <DashboardPage />
                  </Suspense>
                </ErrorBoundary>
              }
            />
            <Route
              path="upload/*"
              element={
                <ErrorBoundary>
                  <Suspense
                    fallback={
                      <div className="text-green-700 text-lg mt-20 text-center">
                        Loading upload…
                      </div>
                    }
                  >
                    <UploadPage />
                  </Suspense>
                </ErrorBoundary>
              }
            />
          </Routes>
        </div>
      </main>
      <footer className="bg-blue-50 py-3 text-center text-sm text-blue-400 shadow-inner">
        &copy; {new Date().getFullYear()} AI Invest Assistant – Host App
      </footer>
    </div>
  );
}
